Add change log entry for changes between 0.3.0-ballot and the Aug balot version (https://github.com/hl7au/au-fhir-core/issues/141)
hl7au/au-fhir-core pull request #143
Opened 2024-04-03 22:07 UTC by dbojicic

Fixes #141.

Changes made:
1. Enabled Change Log in the main menu
2. Added some placeholder text in the Change Log to indicate the kind of the content to be added soon

2024-04-03 23:55 UTC, dt-r requested changes
Remove the change tracking on the Home page. That is the purpose of the change log.

If this is merged first, Steph's PR has to be updated. If done the other way this PR needs to be updated.

2024-04-04 23:54 UTC, dbojicic commented
@dt-r, PR updates, please review again.

2024-04-05 00:09 UTC, dt-r commented on input/pagecontent/changes.md
> +  - Procedure.bodySite [FHIR-45017](https://jira.hl7.org/browse/FHIR-45017)
think this point on bodySite should also state that added profile specific implementation guidance on including body site information

2024-04-05 00:09 UTC, dt-r requested changes
one tweak

2024-04-05 00:40 UTC, dbojicic commented
Updated, please review again.

2024-04-05 01:15 UTC, dt-r commented on input/pagecontent/changes.md
> +  - Procedure.bodySite [FHIR-45017](https://jira.hl7.org/browse/FHIR-45017). Additionally, we've added profile-specific implementation guidance on including body site information.
The JIRA looks divorced from the inclusion of guidance. Make it:
`- Procedure.bodySite and added profile-specific implementation guidance on including bodysite information [FHIR-45017](https://jira.hl7.org/browse/FHIR-45017). `

2024-04-05 02:07 UTC, dt-r approved these changes

2024-04-05 02:09 UTC, merged