Removed Must Support from Condition.asserter (https://jira.hl7.org/browse/FHIR-45127)
hl7au/au-fhir-core pull request #153
Opened 2024-04-23 01:31 UTC by dbojicic

Fixes https://jira.hl7.org/browse/FHIR-45127.

Fix for AU Core R1 Ballot for Comment issue FHIR-45127, resolved as Persuasive in [aucore-blockvote-2](https://confluence.hl7.org/display/HAFWG/aucore-blockvote-2). 

Changes: 
- removed Must Support from Condition.asserter in AU Core Condition
- updated Change Log

2024-04-24 05:38 UTC, dt-r requested changes
In addition to the comments, need to change general-requirements.md to remove references to asserter and recorder.

2024-04-24 05:38 UTC, dt-r commented on input/resources/au-core-condition.xml
> -    <element id="Condition.asserter">
Missing removal of Condition.remover

2024-04-24 20:36 UTC, dbojicic commented on input/resources/au-core-condition.xml
> -    <element id="Condition.asserter">
Done

2024-04-24 20:42 UTC, dbojicic commented
> In addition to the comments, need to change general-requirements.md to remove references to asserter and recorder.

Done

2024-04-26 03:06 UTC, dt-r approved these changes

2024-04-26 03:10 UTC, merged