Removal of Must Support from the encounter elements (aucore-blockvote-4)
hl7au/au-fhir-core pull request #154
Opened 2024-04-26 07:53 UTC by dbojicic

This PR addresses issues from the AU Core R1 Ballot for Comment aucore-blockvote-4: https://confluence.hl7.org/display/HAFWG/aucore-blockvote-4

This PR fixes the following issues:
- https://jira.hl7.org/browse/FHIR-45222
- https://jira.hl7.org/browse/FHIR-45218
- https://jira.hl7.org/browse/FHIR-45189
- https://jira.hl7.org/browse/FHIR-45134
- https://jira.hl7.org/browse/FHIR-45123

Changes:

JIRA | Changes
---- | ----
https://jira.hl7.org/browse/FHIR-45222 | Removed MS from encounter in AU Core Smoking Status profile<br>Updated Change Log
 https://jira.hl7.org/browse/FHIR-45218 | Removed MS from encounter in AU Core Immunization profile<br>Removed encounter from immunization-covid-1 example<br>Updated Change Log
https://jira.hl7.org/browse/FHIR-45189 | Removed MS from encounter  in AU Core Condition profile<br>Removed encounter from condition-cellulitis example<br>Updated Change Log
https://jira.hl7.org/browse/FHIR-45134 | Removed MS from encounter in AU Core Blood Pressure, AU Core Body Height, AU Core Body Weight, AU Core Heart Rate, AU Core Respiration Rate, and AU Core Waist Circumference profiles<br>Removed encounter from bloodpressure-data-absent example<br>Updated Change Log
https://jira.hl7.org/browse/FHIR-45123 | Removed MS from encounter in AU Core AllergyIntolerance profile<br> Removed encounter from allergyintolerance-noneknown example<br>Updated Change Log

2024-04-29 05:31 UTC, dt-r requested changes
Recommend retaining encounter reference in a few examples to support the use of AU Core Encounter.

Also suggest quick review of examples principles in IG to check that only doing Must Support elements is a strong SHOULD not a SHALL.

2024-04-30 11:24 UTC, dbojicic commented
> Recommend retaining encounter reference in a few examples to support the use of AU Core Encounter.
> 
> Also suggest quick review of examples principles in IG to check that only doing Must Support elements is a strong SHOULD not a SHALL.

Reinstated encounter references in a few profiles. 

It is a SHOULD.

2024-05-01 02:33 UTC, dt-r commented
Approve changed made. One additional change suggested to remove Encounter consultation example since it is no longer referenced by an example.

2024-05-01 02:33 UTC, dt-r approved these changes

2024-05-01 02:34 UTC, merged