Add blurb about obligation flag.
hl7au/au-fhir-core pull request #238
Opened 2024-07-24 04:44 UTC by JayMurdoch

Add blurb about obligation flag similar to must support blurb, based on Agency QA feedback

2024-07-24 21:05 UTC, dt-r requested changes
Rethink what this looks and reads like to determine the method of injection of that obligation sentence. See further information in the inline comment.

2024-07-25 12:07 UTC, JayMurdoch commented on input/pagecontent/general-requirements.md
> +In AU Core, the meaning of *Must Support* is specified in terms of [Obligation Codes](https://hl7.org/fhir/extensions/CodeSystem-obligation.html) in [obligation extensions](https://hl7.org/fhir/exten
Shifted to same place as Must Support element. 

Is there a need to add detail of how obligations are rendered in raw also?

2024-07-29 05:23 UTC, dt-r commented on input/pagecontent/general-requirements.md
> +In AU Core, the meaning of *Must Support* is specified in terms of [Obligation Codes](https://hl7.org/fhir/extensions/CodeSystem-obligation.html) in [obligation extensions](https://hl7.org/fhir/exten
Re your question above - depends on what you were trying to add. I'm reviewing whether you a) achieved what the blurb of this PR is (which is what you say it is) and b) if after the change is introduced the IG is of equivalent or better quality.

2024-07-29 05:34 UTC, dt-r commented on input/pagecontent/general-requirements.md
> +##### Presentation of Must Support and obligations in table views
Capitalise Obligation. Headings should be 
- Presentation of elements labelled Must Support and Obligation in profiles
- Presentation of elements labelled Must Support and Obligation in table views

2024-07-29 05:37 UTC, dt-r commented on input/pagecontent/general-requirements.md
> +The elements labelled *Must Support* in these views are flagged with an <span style="padding-left: 3px; padding-right: 3px; color: white; background-color: red" title="This element must be supported"
Replace "The elements with defined obligations" to be "The elements labelled with Obligation in these views are"

Then go on to rephrase the rest of this section now that it is about Must Support and Obligation e.g. "Implementers should refer to the "Key Elements Table" to see the full set of elements that are mandatory or *Must Support* or with Obligations, and the full set of terminology requirements."

2024-07-29 05:37 UTC, dt-r commented on input/pagecontent/general-requirements.md
>  Implementers should take note that the full set of constraints (i.e. invariants) are only presented in the "Detailed Descriptions" tab or the raw representation (e.g. XML or JSON) of the profile.
This sentence on Implementers should take note is no longer true. It can be removed entirely.

2024-07-29 05:38 UTC, dt-r requested changes
See inline comments.

2024-10-24 05:10 UTC, closed without merging