Move documentation of chaining to render as part of patient/practitioner search parameter documentation
hl7au/au-fhir-core pull request #266
Opened 2024-10-13 05:00 UTC by dbojicic

Changes:
- Moved the documentation for patient.identifier and practitioner.identifier in the profile notes to be included as part of the patient/ practitioner documentation on the profile pages
-  Removed text from AU Core Responder and Requester CapabilityStatements

2024-10-14 21:02 UTC, dt-r commented
This is part of moving to auto-narrative gen in capability statements. I don't think we should be spending effort reviewing narrative changes in the capability statements when we need to repeat that effort for the auto-narrative gen.

2024-10-14 22:29 UTC, dbojicic commented
> This is part of moving to auto-narrative gen in capability statements. I don't think we should be spending effort reviewing narrative changes in the capability statements when we need to repeat that effort for the auto-narrative gen.

This PR removes the narrative from capability statements (will update the title to mention it) and updates the profile pages.

2024-11-21 03:25 UTC, dbojicic commented on input/includes/observation_parameters.md
> +        <td><b>SHALL</b></td>
add test comment

2024-11-28 11:46 UTC, JayMurdoch commented on input/includes/observation_parameters.md
> +        <td><b>SHALL</b></td>
Conformance changed from MAY to SHALL. Previously, patient was MAY and patient.identifier was SHOULD. CapabilityStatements are MAY for patient, including chained search patient.identifer. Please clarify the change.

2024-11-28 11:47 UTC, JayMurdoch commented on input/includes/observation_vitalsigns_parameters.md
> +        <td><b>SHALL</b></td>
As above - Conformance changed from MAY to SHALL. Previously, patient was MAY and patient.identifier was SHOULD. CapabilityStatements are MAY for patient, including chained search patient.identifer. Please clarify the change.

2024-11-28 11:57 UTC, JayMurdoch commented on input/intro-notes/StructureDefinition-au-core-allergyintolerance-notes.md
> +        <td>The requester <b>SHALL</b> provide at least an id value and <b>MAY</b> provide both the Type and id values. The responder <b>SHALL</b> support both.<br/><br/>The requester <b>SHALL</b> pr
**This comment applies to ALL profiles included in this PR:**
"The requester SHALL provide both the system and code values. The responder SHALL support both." which comes from the chained search, now reads as though it belongs to patient.  Suggest linking it to the chained search detail - either by placing under chained search paragraph or in same paragraph. 
This text is not in any of the Requester or Responder CapabilityStatements for profiles listed in this PR.

2024-11-28 11:59 UTC, JayMurdoch requested changes
See inline comments.

2025-01-02 00:38 UTC, dbojicic commented on input/includes/observation_parameters.md
> +        <td><b>SHALL</b></td>
Fixed.

2025-01-02 00:38 UTC, dbojicic commented on input/includes/observation_vitalsigns_parameters.md
> +        <td><b>SHALL</b></td>
Fixed.

2025-01-06 01:22 UTC, dbojicic commented on input/intro-notes/StructureDefinition-au-core-allergyintolerance-notes.md
> +        <td>The requester <b>SHALL</b> provide at least an id value and <b>MAY</b> provide both the Type and id values. The responder <b>SHALL</b> support both.<br/><br/>The requester <b>SHALL</b> pr
Thanks @JayMurdoch. I removed the text in question. Chained searches using patient.identifier follow all standard rules for the identifier parameter as defined in the IG. I think that stating these rules in the documentation for patient.identifier  chained search may lead to confusion, making it seem as though the chained searches require additional rules beyond what's already defined.
Noting that the practitioner.identifier documentation in AU Core PractitionerRole does not reiterate the rules for Practitioner identifier search parameter.

2025-01-14 01:27 UTC, JayMurdoch commented on input/includes/observation_parameters.md
> +        <td><b>SHALL</b></td>
Reviewed.

2025-01-14 01:29 UTC, JayMurdoch commented on input/includes/observation_vitalsigns_parameters.md
> +        <td><b>SHALL</b></td>
Reviewed change. 
Now that this conformance verb is MAY, this line in the table should be shifted below SHALL/SHOULD.

2025-01-14 01:32 UTC, JayMurdoch commented on input/intro-notes/StructureDefinition-au-core-allergyintolerance-notes.md
> +        <td>The requester <b>SHALL</b> provide at least an id value and <b>MAY</b> provide both the Type and id values. The responder <b>SHALL</b> support both.<br/><br/>The requester <b>SHALL</b> pr
Reviewed.

2025-01-14 01:42 UTC, JayMurdoch requested changes
Two minor changes required.

2025-01-14 07:15 UTC, dbojicic commented on input/includes/observation_parameters.md
> +        <td><b>SHALL</b></td>
Done

2025-01-14 07:16 UTC, dbojicic commented on input/includes/observation_vitalsigns_parameters.md
> +        <td><b>SHALL</b></td>
Done

2025-01-14 11:47 UTC, JayMurdoch commented on input/includes/observation_vitalsigns_parameters.md
> +        <td><b>SHALL</b></td>
Reviewed.

2025-01-14 11:48 UTC, JayMurdoch approved these changes

2025-01-14 11:49 UTC, merged