Add explanation of Obligation flag to General Guidance page
hl7au/au-fhir-core pull request #276
Opened 2024-10-24 05:16 UTC by JayMurdoch

Fix for [FHIR-47092](https://jira.hl7.org/browse/FHIR-47092)

* Added explanation of O and SO flag in "Presentation of elements labelled Must Support and Obligation in table views"
* Deleted paragraph starting "Implementers should take note..." as this is no longer true, requested in related PR that is now closed:  https://github.com/hl7au/au-fhir-core/pull/238
* Added Obligation example under "Presentation of elements labelled Must Support and Obligation in raw representations"

2025-01-13 04:34 UTC, dt-r requested changes
The section needs restructuring, not small additions into existing structure. The beginnings of such a restructure is below - REVIEW IT, don't copy paste:

#### Presentation of Must Support and Obligation in profiles
All elements labelled Must Support in AU Core are accompanied by an explicit obligation that identifies the expectations for one or more actors. Each profile is presented in different formal views under tabs labelled "Differential Table", "Key Elements Table", and "Snapshot Table". The elements labelled *Must Support* and *Obligation* in these views are flagged with <span style="padding-left: 3px; padding-right: 3px; color: white; background-color: red" title="This element must be supported">S</span><span style="padding-left: 3px; padding-right: 3px; color: white; background-color: red" title="This element has obligations">O</span> as shown below. 

_insert image of AU Core AllergyIntolerance profile_
*Figure 1: Key Elements Table View*
<br/>

Implementers should refer to the "Key Elements Table" to see the full set of elements that are mandatory or *Must Support* or with Obligations, and the full set of terminology requirements. Implementers should take note that the full set of constraints (i.e. invariants) are only presented in the "Detailed Descriptions" tab or the raw representation (e.g. XML or JSON) of the profile. 

##### Presentation of elements with Must Support and Obligation in raw representations

When viewing the raw representation (e.g. XML or JSON) of a profile, elements with *Must Support* are flagged as `mustSupport` set to "true", and *Obligations* are included by [obligation extensions](https://hl7.org/fhir/extensions/StructureDefinition-obligation.html) as shown in the example below. 

Example: AU Core AllergyIntolerance profile showing clinicalStatus with *Must Support* and *Obligation* on clinicalStatus
~~~
{
    "resourceType" : "StructureDefinition",
    ...
    "url" : "http://hl7.org.au/fhir/core/StructureDefinition/au-core-allergyintolerance",  
    ...
        {
      "id" : "AllergyIntolerance.clinicalStatus",
      "extension" : [{
        "extension" : [{
          "url" : "code",
          "valueCode" : "SHALL:populate-if-known"
        },
        {
          "url" : "actor",
          "valueCanonical" : "http://hl7.org.au/fhir/core/ActorDefinition/au-core-actor-responder"
        }],
        "url" : "http://hl7.org/fhir/StructureDefinition/obligation"
      },
      {
        "extension" : [{
          "url" : "code",
          "valueCode" : "SHALL:no-error"
        },
        {
          "url" : "actor",
          "valueCanonical" : "http://hl7.org.au/fhir/core/ActorDefinition/au-core-actor-requester"
        }],
        "url" : "http://hl7.org/fhir/StructureDefinition/obligation"
      }],
      "path" : "AllergyIntolerance.clinicalStatus",
      "mustSupport" : true
    },
    ...
}
~~~

2025-01-13 12:28 UTC, JayMurdoch commented
> The section needs restructuring, not small additions into existing structure. The beginnings of such a restructure is below - REVIEW IT, don't copy paste:
> 
> `#### Presentation of Must Support and Obligation in profiles `All elements labelled Must Support in AU Core are accompanied by an explicit obligation that identifies the expectations for one or more actors. Each profile is presented in different formal views under tabs labelled "Differential Table", "Key Elements Table", and "Snapshot Table". The elements labelled _Must Support_ and _Obligation_ in these views are flagged with `<span style="padding-left: 3px; padding-right: 3px; color: white; background-color: red" title="This element must be supported">S</span><span style="padding-left: 3px; padding-right: 3px; color: white; background-color: red" title="This element has obligations">O</span>` as shown below.
> 
> _insert image of AU Core AllergyIntolerance profile_ _Figure 1: Key Elements Table View_ `<br/>`
> 
> Implementers should refer to the "Key Elements Table" to see the full set of elements that are mandatory or _Must Support_ or with Obligations, and the full set of terminology requirements. Implementers should take note that the full set of constraints (i.e. invariants) are only presented in the "Detailed Descriptions" tab or the raw representation (e.g. XML or JSON) of the profile.
> 
> ##### Presentation of elements with Must Support and Obligation in raw representations
> When viewing the raw representation (e.g. XML or JSON) of a profile, elements with _Must Support_ are flagged as `mustSupport` set to "true", and _Obligations_ are included by`[obligation extensions](https://hl7.org/fhir/extensions/StructureDefinition-obligation.html)`as shown in the example below.
> 
> Example: AU Core AllergyIntolerance profile showing clinicalStatus with _Must Support_ and _Obligation_ on clinicalStatus
> 
> ```
> {
>     "resourceType" : "StructureDefinition",
>     ...
>     "url" : "http://hl7.org.au/fhir/core/StructureDefinition/au-core-allergyintolerance",  
>     ...
>         {
>       "id" : "AllergyIntolerance.clinicalStatus",
>       "extension" : [{
>         "extension" : [{
>           "url" : "code",
>           "valueCode" : "SHALL:populate-if-known"
>         },
>         {
>           "url" : "actor",
>           "valueCanonical" : "http://hl7.org.au/fhir/core/ActorDefinition/au-core-actor-responder"
>         }],
>         "url" : "http://hl7.org/fhir/StructureDefinition/obligation"
>       },
>       {
>         "extension" : [{
>           "url" : "code",
>           "valueCode" : "SHALL:no-error"
>         },
>         {
>           "url" : "actor",
>           "valueCanonical" : "http://hl7.org.au/fhir/core/ActorDefinition/au-core-actor-requester"
>         }],
>         "url" : "http://hl7.org/fhir/StructureDefinition/obligation"
>       }],
>       "path" : "AllergyIntolerance.clinicalStatus",
>       "mustSupport" : true
>     },
>     ...
> }
> ```

I have incorporated with some minor changes. Please review.

2025-01-13 21:28 UTC, dt-r requested changes
See inline comments.

2025-01-13 21:28 UTC, dt-r commented on input/pagecontent/general-requirements.md
> +    <img src="allergyintolerance-keyelementstable.png" alt="AU Core AllergyIntolerance Key Elements Table" style="width:100%"/>
To the image add a red circle around "Key Elements" and a red circle around "SO". Similar to how there are red circles in the instructions on voting on this page (when you expand the instructions): https://confluence.hl7.org/display/HAFWG/AU+Core+R1+Ballot+for+Working+Standard%3A+aucore-blockvote-8

Do not add arrows or text, just the red circles.

2025-01-13 21:28 UTC, dt-r commented on input/pagecontent/general-requirements.md
> +#### Presentation of Must Support and Obligation in profiles
"Obligation" isn't to be capitalised with italics like _Must Support_. Change to lower case and no italics, in some cases the sentences need to be reworked.
Likely change:
* "an explicit *Obligation* that" to "an explicit obligation that"
* "The elements with *Must Support* and *Obligation*" to "Elements flagged with *Must Support* and stated obligations"
* "that are mandatory or Must Support or with Obligations" to "that are mandatory or Must Support with obligations"
* "Obligations are defined by the [Obligation Extension](https://hl7.org/fhir/extensions/StructureDefinition-obligation.html)" to "obligations are defined in the [Obligation Extension](https://hl7.org/fhir/extensions/StructureDefinition-obligation.html)"
* "Example: AU Core AllergyIntolerance profile with Must Support and Obligation on clinicalStatus." with Example: AU Core AllergyIntolerance profile with Must Support and obligations on clinicalStatus."

2025-01-13 23:22 UTC, JayMurdoch commented on input/pagecontent/general-requirements.md
> +    <img src="allergyintolerance-keyelementstable.png" alt="AU Core AllergyIntolerance Key Elements Table" style="width:100%"/>
Red circles added.

2025-01-13 23:31 UTC, JayMurdoch commented on input/pagecontent/general-requirements.md
> +#### Presentation of Must Support and Obligation in profiles
Amended, thanks.

2025-01-14 06:01 UTC, dt-r approved these changes

2025-01-14 06:01 UTC, merged