Changes for _include (FHIR-48719, FHIR-48718)
hl7au/au-fhir-core pull request #286
Opened 2024-11-04 08:27 UTC by dbojicic

This PR provides fixes for [FHIR-48718](https://jira.hl7.org/browse/FHIR-48718) and [FHIR-48719](https://jira.hl7.org/browse/FHIR-48719).

2024-11-04 12:41 UTC, JayMurdoch commented on input/resources/au-core-requester.xml
> +<valueCode value="SHALL"/>
Change from SHALL to SHOULD

2024-11-04 12:42 UTC, JayMurdoch commented on input/resources/au-core-responder.xml
> +<valueCode value="SHALL"/>
Change from SHALL to SHOULD

2024-11-04 12:43 UTC, JayMurdoch commented on input/resources/au-core-responder.xml
> +<searchInclude value="MedicationRequest:medication">
Add blurb to documentation value

2024-11-04 12:44 UTC, JayMurdoch approved these changes

2024-11-04 12:54 UTC, JayMurdoch requested changes
See inline comments.

2024-11-05 01:13 UTC, dbojicic commented on input/resources/au-core-requester.xml
> +<valueCode value="SHALL"/>
done

2024-11-05 01:13 UTC, dbojicic commented on input/resources/au-core-responder.xml
> +<valueCode value="SHALL"/>
Done

2024-11-05 04:00 UTC, dbojicic commented on input/resources/au-core-requester.xml
> +<searchInclude value="MedicationRequest:medication">
done

2024-11-05 04:00 UTC, dbojicic commented on input/resources/au-core-responder.xml
> +<searchInclude value="MedicationRequest:medication">
done

2024-11-05 05:19 UTC, JayMurdoch commented on input/resources/au-core-requester.xml
> +<documentation value="The requester **SHALL** provide a value precise to the *second + time offset*.&#xA;&#xA;The responder **SHALL** support a value precise to the *second + time offset*. &#xA;&#xA;
This change is not outlined in the associated Jira tickets.

2024-11-05 05:20 UTC, JayMurdoch requested changes
One further comment, thanks.

2024-11-05 08:52 UTC, JayMurdoch approved these changes

2024-11-11 10:48 UTC, brettesler-ext approved these changes

2024-11-11 13:29 UTC, merged