Remove conformance for create, update, delete, vread, patch, history-instance from CapStats (FHIR-46060)
hl7au/au-fhir-core pull request #289
Opened 2024-11-12 12:30 UTC by JayMurdoch

Fix for [FHIR-46060](https://jira.hl7.org/browse/FHIR-46060)

* Remove all instances of MAY support create, update, delete, vread, patch, history-instance from Responder and Requester Capstats.

2024-11-14 22:54 UTC, dbojicic commented on input/resources/au-core-requester.xml
>  </extension>
Medication resource MAY support search-type still present.

2024-11-15 00:51 UTC, dbojicic commented on input/resources/au-core-responder.xml
>  </extension>
Medication resource search-type MAY interaction still present.

2024-11-15 00:53 UTC, dbojicic requested changes
Please see inline comments.

2024-11-17 12:06 UTC, JayMurdoch commented on input/resources/au-core-requester.xml
>  </extension>
Removed, thanks.

2024-11-17 12:06 UTC, JayMurdoch commented on input/resources/au-core-responder.xml
>  </extension>
Removed, thanks.

2024-11-18 04:45 UTC, merged