Add guidance on Observation.value and DAR to Missing Data
hl7au/au-fhir-core pull request #293
Opened 2024-11-21 01:27 UTC by JayMurdoch

Fix for [FHIR-47090](https://jira.hl7.org/browse/FHIR-47090)
* Add guidance to Missing Must Support and Optional Data regarding use of DAR when Observation.value is missing.

2025-01-13 02:12 UTC, dt-r commented on input/pagecontent/general-requirements.md
> +In AU Core Observation resources, `Observation.value` is conditionally mandatory. If the source system does not know the value for `Observation.value`, `Observation.dataAbsentReason` **SHALL** be use
Guidance on conditionally mandatory goes in the Missing Must Support and Mandatory Data section. See suggestions below - REVIEW THEM, do not copy paste

Add as the third bullet point under "1. For non-coded data elements where the applicable AU Core profile does not mandate a sub-element

> For some AU Core Observation profiles the Observation.value element is conditionally mandatory, e.g. AU Core Body Height, and in this case the `Observation.dataAbsentReason` element is used with the code "unknown" NOT the [DataAbsentReason extension](http://hl7.org/fhir/R4/extension-data-absent-reason.html).


Add as the TBD

> For some AU Core Observation profiles the Observation.value element is conditionally mandatory, e.g. AU Core Smoking Status, and in this case the `Observation.dataAbsentReason` element is used with the code "unknown" NOT the [DataAbsentReason extension](http://hl7.org/fhir/R4/extension-data-absent-reason.html).

2025-01-13 02:21 UTC, dt-r requested changes
See inline comments.

2025-01-14 00:51 UTC, JayMurdoch commented on input/pagecontent/general-requirements.md
> +In AU Core Observation resources, `Observation.value` is conditionally mandatory. If the source system does not know the value for `Observation.value`, `Observation.dataAbsentReason` **SHALL** be use
Incorporated with some minor changes.

2025-01-15 07:18 UTC, dt-r approved these changes

2025-01-15 07:18 UTC, merged