Improve the example descriptions that are seen on the FHIR Artefacts page
hl7au/au-fhir-core pull request #297
Opened 2024-12-15 00:15 UTC by dbojicic

https://github.com/hl7au/au-fhir-erequesting/pull/103

2025-01-14 04:54 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of an organisation, Bobrester Medical Center, for the *AU Core Organization* profile, with with ABN identifier, type as Medical Center, and contact details inc
Remove additional "with" from "with with ABN identifier"

2025-01-14 04:56 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a patient resource for Mr. Ronny Lawrence Irvine for the *AU Core Patient* profile.The patient identifies as Torres Strait Islander but not of Aboriginal or
Add space between "profile.The patient.."

2025-01-14 04:58 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a General Practitioner role for the *AU Core PractitionerRole*, including an employee number identifier, contact details and and references to the associate
Add profile to "role for the *AU Core PractitionerRole* **profile**...".
Remove extra 'and' from "and and references...".

2025-01-14 05:00 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a Cardiologist role for the *AU Core PractitionerRole*, including a Medicare Provider Number identifier, contact details, and references to the associated P
Add 'profile' to "for the *AU Core PractitionerRole* **profile**,".

2025-01-14 05:07 UTC, JayMurdoch commented on input/ig.xml
>  		<resource>
For AllergyIntolerance/noneknown - change to "Shows an example of an **allergy intolerance** for the *AU Core AllergyIntolerance* **profile**...."

2025-01-14 05:09 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of Penicillin allergy with the reaction manifestation as hives for the *AU Core AllergyIntolerance* profile. Patient: Deangelo HOWE."/>
Add 'a' to "Shows an example of **a** Penicillin allergy...".
Remove title casing from patient name - HOWE to Howe across all instances.

2025-01-14 05:11 UTC, JayMurdoch commented on input/ig.xml
>  		<!--CONDITION EXAMPLES-->
For Condition/ckd - remove 'an' from "Shows an example of **an**..."

2025-01-14 07:31 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a patient resource for Mr. Ronny Lawrence Irvine for the *AU Core Patient* profile.The patient identifies as Torres Strait Islander but not of Aboriginal or
Done

2025-01-14 07:32 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a General Practitioner role for the *AU Core PractitionerRole*, including an employee number identifier, contact details and and references to the associate
Done

2025-01-14 07:33 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a Cardiologist role for the *AU Core PractitionerRole*, including a Medicare Provider Number identifier, contact details, and references to the associated P
Done

2025-01-14 07:33 UTC, dbojicic commented on input/ig.xml
>  		<resource>
Done

2025-01-14 07:34 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of Penicillin allergy with the reaction manifestation as hives for the *AU Core AllergyIntolerance* profile. Patient: Deangelo HOWE."/>
Done

2025-01-14 07:34 UTC, dbojicic commented on input/ig.xml
>  		<!--CONDITION EXAMPLES-->
Done

2025-01-14 11:10 UTC, JayMurdoch commented on input/ig.xml
>  		<resource>
2. For Condition/uti - in description change 'Urinary' to 'urinary'.
3. For Condition/condition-masked - in description change 'Condition' to 'condition'; add commas "Shows an example of a Condition with suppressed data (category and code)**,** where the data requester has access rights to know that data is suppressed**,** for the *AU Core Condition* profile.

2025-01-14 11:11 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows and example of a completed virtual telehealth encounter for the *AU Core Encounter* profile. Patient: Mrs. Anne Bennelong."/>
Change 'and' to 'an': "Shows **and** example..."

2025-01-14 11:17 UTC, JayMurdoch commented on input/ig.xml
>  		<resource>
Immunization/zoster-notgiven: suggest "Shows an example of a vaccination not administered due to...".

2025-01-14 11:19 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a branded medication, Chlorsig (chloramphenicol 0.5%), with one active ingredient for the *AU Core Medication* profile. Includes a medication type extension
Remove 's' from 'strengths'.

2025-01-14 11:25 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a laboratory result for the Total Cholesterol/HDL ratio result for the *AU Core Pathology Result Observation* profile. Patient: Mia Leanne Banks."/>
Remove 2nd result: "Shows an example of a laboratory result for the Total Cholesterol/HDL ratio -result- for..."

2025-01-14 11:27 UTC, JayMurdoch commented on input/ig.xml
>  		<resource>
For Observation/pathresult-covid-1: amend profile name to "AU Core Pathology Result Observation"

2025-01-14 11:29 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of an organisation, Murrabit Public Hospital, for the *AU Core Organization* profile, with an HPI-O, type as Hospital, and contact details including multiple p
Amend 'an' to 'a' for "with **an** HPI-O"

2025-01-14 11:31 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a patient resource for Mia Leanne Banks for the *AU Core Patient* profile. The patient identifies as female gender, uses the pronouns she/her', and has a ve
Remove apostrophe from "she/her'"

2025-01-14 11:32 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a practitioner resource for Dr. Sallie Sutherland with an HPI-I for the *AU Core Practitioner* profile. The resource includes the practitioner's official na
Change 'an' to 'a' for "with **an** HPI-I for.."

2025-01-14 11:32 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a practitioner resource for Dr. Chau Fryer with an HPI-I for the *AU Core Practitioner* profile. The resource includes the practitioner's official name and
Change 'an' to 'a' HPI-I for "with **an** HPI-I for the..."

2025-01-14 11:33 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a practitioner resource for Darleen Mackay with an HPI-I for the *AU Core Practitioner* profile. The resource includes the practitioner's name and identifie
Change 'an' to 'a' HPI-I for "with **an** HPI-I for the..."

2025-01-14 11:36 UTC, JayMurdoch commented on input/ig.xml
>  		<resource>
Reviewed.

2025-01-14 11:36 UTC, JayMurdoch commented on input/ig.xml
>  		<!--CONDITION EXAMPLES-->
Reviewed.

2025-01-14 11:37 UTC, JayMurdoch requested changes
See inline comments.

2025-01-14 12:16 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of allergy intolerance for the *AU Core AllergyIntolerance* profile indicating the patient has no known allergies. Patient: Mr. Li Wang."/>
Improved wording suggested by @steveswinsburg in https://github.com/hl7au/au-fhir-core/pull/303:
"Shows an example of no known allergies for the *AU Core AllergyIntolerance* profile. Patient: Mr. Li Wang."

2025-01-15 06:02 UTC, dbojicic commented on input/ig.xml
>  		<resource>
Done

2025-01-15 06:06 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows and example of a completed virtual telehealth encounter for the *AU Core Encounter* profile. Patient: Mrs. Anne Bennelong."/>
fixed

2025-01-15 06:06 UTC, dbojicic commented on input/ig.xml
>  		<resource>
Done

2025-01-15 06:07 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a branded medication, Chlorsig (chloramphenicol 0.5%), with one active ingredient for the *AU Core Medication* profile. Includes a medication type extension
Done

2025-01-15 06:10 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a laboratory result for the Total Cholesterol/HDL ratio result for the *AU Core Pathology Result Observation* profile. Patient: Mia Leanne Banks."/>
Done

2025-01-15 06:11 UTC, dbojicic commented on input/ig.xml
>  		<resource>
Done

2025-01-15 06:11 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of an organisation, Murrabit Public Hospital, for the *AU Core Organization* profile, with an HPI-O, type as Hospital, and contact details including multiple p
Done

2025-01-15 06:12 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a patient resource for Mia Leanne Banks for the *AU Core Patient* profile. The patient identifies as female gender, uses the pronouns she/her', and has a ve
Done

2025-01-15 06:12 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a practitioner resource for Dr. Sallie Sutherland with an HPI-I for the *AU Core Practitioner* profile. The resource includes the practitioner's official na
Done

2025-01-15 06:12 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a practitioner resource for Dr. Chau Fryer with an HPI-I for the *AU Core Practitioner* profile. The resource includes the practitioner's official name and
Done

2025-01-15 06:12 UTC, dbojicic commented on input/ig.xml
> +			<description value="Shows an example of a practitioner resource for Darleen Mackay with an HPI-I for the *AU Core Practitioner* profile. The resource includes the practitioner's name and identifie
Done

2025-01-15 10:36 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of an organisation, Bobrester Medical Center, for the *AU Core Organization* profile, with with ABN identifier, type as Medical Center, and contact details inc
Reviewed.

2025-01-15 10:36 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a patient resource for Mr. Ronny Lawrence Irvine for the *AU Core Patient* profile.The patient identifies as Torres Strait Islander but not of Aboriginal or
Reviewed.

2025-01-15 10:37 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a Cardiologist role for the *AU Core PractitionerRole*, including a Medicare Provider Number identifier, contact details, and references to the associated P
Reviewed.

2025-01-15 10:45 UTC, JayMurdoch commented on input/ig.xml
>  		<resource>
Reviewed - 2 does not have suggested changes, but upon re-read, happy to leave.

2025-01-15 10:46 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows and example of a completed virtual telehealth encounter for the *AU Core Encounter* profile. Patient: Mrs. Anne Bennelong."/>
Reviewed.

2025-01-15 10:46 UTC, JayMurdoch commented on input/ig.xml
>  		<resource>
Reviewed.

2025-01-15 10:46 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a branded medication, Chlorsig (chloramphenicol 0.5%), with one active ingredient for the *AU Core Medication* profile. Includes a medication type extension
Reviewed.

2025-01-15 10:47 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a laboratory result for the Total Cholesterol/HDL ratio result for the *AU Core Pathology Result Observation* profile. Patient: Mia Leanne Banks."/>
Reviewed.

2025-01-15 10:47 UTC, JayMurdoch commented on input/ig.xml
>  		<resource>
Reviewed.

2025-01-15 10:48 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of an organisation, Murrabit Public Hospital, for the *AU Core Organization* profile, with an HPI-O, type as Hospital, and contact details including multiple p
Reviewed.

2025-01-15 10:49 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a patient resource for Mia Leanne Banks for the *AU Core Patient* profile. The patient identifies as female gender, uses the pronouns she/her', and has a ve
Reviewed.

2025-01-15 10:49 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a practitioner resource for Dr. Sallie Sutherland with an HPI-I for the *AU Core Practitioner* profile. The resource includes the practitioner's official na
Reviewed.

2025-01-15 10:50 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a practitioner resource for Darleen Mackay with an HPI-I for the *AU Core Practitioner* profile. The resource includes the practitioner's name and identifie
Reviewed.

2025-01-15 10:50 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of Penicillin allergy with the reaction manifestation as hives for the *AU Core AllergyIntolerance* profile. Patient: Deangelo HOWE."/>
Reviewed.

2025-01-15 10:51 UTC, JayMurdoch commented on input/ig.xml
> +			<description value="Shows an example of a General Practitioner role for the *AU Core PractitionerRole*, including an employee number identifier, contact details and and references to the associate
Reviewed.

2025-01-15 10:51 UTC, JayMurdoch approved these changes

2025-01-15 21:08 UTC, merged