Terminology page changes to add Publisher (FHIR-47175)
hl7au/au-fhir-core pull request #298
Opened 2024-12-15 20:44 UTC by dbojicic

Fix for [FHIR-47175](https://jira.hl7.org/browse/FHIR-47175).

2025-01-14 01:51 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +This implementation guide does not define any unique code systems. The code systems used in this guide are defined in the base FHIR specification, [AU Base](https://build.fhir.org/ig/hl7au/au-fhir-ba
Remove extra bracket from NCTS link - not rendering: [NCTS](**(**https://www.healthterminologies.gov.au/)

2025-01-14 01:52 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +  <li><strong>CodeSystem:</strong> The title of a code system.</li>
Change to align to value set: "The title of **the** code system."

2025-01-14 03:14 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|[DegreeLicenseCertificate AU](https://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-v2-0360.html)|[hl7VS-degreeLicenseCertificate - AU Extended](https://build.fhir.org/ig/hl7au/au-fhir-base/Val
Change publisher to HL7 Australia.

2025-01-14 03:28 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|[LOINC](https://www.healthterminologies.gov.au/access-clinical-terminology/access-fhir-terminology-resources/code-systems/?ui:filter=loinc)|[Australian Pronouns](https://healthterminologies.gov.au/f
Direct link to LOINC code system: https://www.healthterminologies.gov.au/integration/R4/fhir/CodeSystem/LOINC-2.78

2025-01-14 03:41 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|[SNOMED CT (Australian extension)](https://www.healthterminologies.gov.au/access-clinical-terminology/access-fhir-terminology-resources/code-systems/?ui:filter=snomed)|[Adverse Reaction Agent](https
Direct link to SNOMED CT code system https://www.healthterminologies.gov.au/integration/R4/fhir/CodeSystem/32506021000036107-20241231

2025-01-14 04:10 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|[ActCode](https://terminology.hl7.org/5.3.0/CodeSystem-v3-ActCode.html)|[ActEncounterCode](https://terminology.hl7.org/5.5.0/ValueSet-v3-ActEncounterCode.html)|HL7 Terminology|Health Level Seven Int
As per AU Base, amend instances of "HL7 Terminology" to "HL7 Terminology (THO)"

2025-01-14 04:20 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|ValueSet|Profile where used|Available from|
Change "Profile where used" to "Profiles and Extensions where used:"

2025-01-14 04:23 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|[DataAbsentReason](http://terminology.hl7.org/CodeSystem/data-absent-reason)|[Australian Pronouns](https://healthterminologies.gov.au/fhir/ValueSet/australian-pronouns-1), [Gender Identity Response]
Add Biological Sex value set: https://healthterminologies.gov.au/fhir/ValueSet/biological-sex-1

2025-01-14 04:25 UTC, JayMurdoch requested changes
See inline comments.

2025-01-14 07:19 UTC, dbojicic commented on input/pagecontent/terminology.md
> +This implementation guide does not define any unique code systems. The code systems used in this guide are defined in the base FHIR specification, [AU Base](https://build.fhir.org/ig/hl7au/au-fhir-ba
Done

2025-01-14 07:20 UTC, dbojicic commented on input/pagecontent/terminology.md
> +  <li><strong>CodeSystem:</strong> The title of a code system.</li>
Will leave aligned with AU Base. No change.

2025-01-14 07:21 UTC, dbojicic commented on input/pagecontent/terminology.md
> +|[DegreeLicenseCertificate AU](https://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-v2-0360.html)|[hl7VS-degreeLicenseCertificate - AU Extended](https://build.fhir.org/ig/hl7au/au-fhir-base/Val
Done

2025-01-14 07:21 UTC, dbojicic commented on input/pagecontent/terminology.md
> +|[ActCode](https://terminology.hl7.org/5.3.0/CodeSystem-v3-ActCode.html)|[ActEncounterCode](https://terminology.hl7.org/5.5.0/ValueSet-v3-ActEncounterCode.html)|HL7 Terminology|Health Level Seven Int
Done

2025-01-14 07:22 UTC, dbojicic commented on input/pagecontent/terminology.md
> +|ValueSet|Profile where used|Available from|
Done

2025-01-14 07:25 UTC, dbojicic commented on input/pagecontent/terminology.md
> +|[DataAbsentReason](http://terminology.hl7.org/CodeSystem/data-absent-reason)|[Australian Pronouns](https://healthterminologies.gov.au/fhir/ValueSet/australian-pronouns-1), [Gender Identity Response]
Done

2025-01-14 11:39 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +This implementation guide does not define any unique code systems. The code systems used in this guide are defined in the base FHIR specification, [AU Base](https://build.fhir.org/ig/hl7au/au-fhir-ba
Reviewed.

2025-01-14 11:39 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +  <li><strong>CodeSystem:</strong> The title of a code system.</li>
Noted, thanks.

2025-01-14 11:40 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|[DegreeLicenseCertificate AU](https://build.fhir.org/ig/hl7au/au-fhir-base/CodeSystem-au-v2-0360.html)|[hl7VS-degreeLicenseCertificate - AU Extended](https://build.fhir.org/ig/hl7au/au-fhir-base/Val
Reviewed.

2025-01-14 11:44 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|ValueSet|Profile where used|Available from|
Add s to profile and extension "Profile and Extension where used" to "Profiles and Extensions where used"

2025-01-14 11:45 UTC, JayMurdoch requested changes
Some minor changes required

2025-01-15 05:46 UTC, dbojicic commented on input/pagecontent/terminology.md
> +|[ActCode](https://terminology.hl7.org/5.3.0/CodeSystem-v3-ActCode.html)|[ActEncounterCode](https://terminology.hl7.org/5.5.0/ValueSet-v3-ActEncounterCode.html)|HL7 Terminology|Health Level Seven Int
Done

2025-01-15 05:46 UTC, dbojicic commented on input/pagecontent/terminology.md
> +|ValueSet|Profile where used|Available from|
Done

2025-01-15 10:32 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|[ActCode](https://terminology.hl7.org/5.3.0/CodeSystem-v3-ActCode.html)|[ActEncounterCode](https://terminology.hl7.org/5.5.0/ValueSet-v3-ActEncounterCode.html)|HL7 Terminology|Health Level Seven Int
Reviewed.

2025-01-15 10:34 UTC, JayMurdoch requested changes
One last fix

2025-01-15 21:33 UTC, dbojicic commented on input/pagecontent/terminology.md
> +|ValueSet|Profile where used|Available from|
Done

2025-01-15 23:03 UTC, JayMurdoch commented on input/pagecontent/terminology.md
> +|ValueSet|Profile where used|Available from|
Reviewed.

2025-01-15 23:03 UTC, JayMurdoch approved these changes

2025-01-15 23:03 UTC, merged